### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by thomaslc66** [flutter-clutter/flutter-simple-edge-detection#13]
Hello,

First thank you for you work and for the amazing tutorial you've done, this is really well done.

I've tried to use you app and it was quite a challenge, but at the end i've manage to integrate it to my project.
Maybe you can help me and let me know where and why when the cropping is done, the preview is in black and white and where can i change that?
Secondly I think this is not working with camera 0.60+ ? or...
Last one in you example as you have more than one Floating button, you need to add `herotag` to identify floating button.

Thank you for you answer.

Thomas

**Comment by flutter-clutter** [comment]
Hey @thomaslc66.
Please have a look at this issue: https://github.com/flutter-clutter/flutter-simple-edge-detection/issues/7

**Comment by flutter-clutter** [comment]
Regarding the compatability with camera 0.60+: I don't know. From the pub page I can not identify any breaking changes after 0.50 that could affect this. Without having tried this particular version I guess it should work. What kind of error do you get?

**Comment by flutter-clutter** [comment]
I'm gonna close this. If the error still persists, don't hesitate to open a new one. Cheers :)
