### ISSUE TITLE
'vsync != null': is not true

### ISSUE THREAD

**Issue by beran035** [flutter-clutter/flutter-simple-edge-detection#16]
after taking picture error: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 245 pos 14: 'vsync != null': is not true.

**Comment by flutter-clutter** [comment]
Hey @beran035.
I'm afraid I can not directly help you as it does not seem to an issue directly related to this repository. There might be artifacts from previous builds preventing it from working properly. However, I can point you to a SO post addressing your issue: https://stackoverflow.com/questions/63583840/packageflutter-src-animation-animation-controller-dart-failed-assertion-lin

If this doesn't help, just reopen and comment.
