### ISSUE TITLE
Issue in FFI package.

### ISSUE THREAD

**Issue by waqaskhan409** [flutter-clutter/flutter-simple-edge-detection#18]
Hi,
I hope all is well. Please can you check the FFI package version 1.0.0 https://pub.dev/packages/ffi/example. Some methods are deprecated and some methods are gone. Like, the allocation is not available and UTF8 is not accepting path as a string and so forth. Let me know if you are still maintaining this package. 
Best Wishes,
Waqas

**Comment by flutter-clutter** [comment]
Should be fixed in #19 :)
