### ISSUE TITLE
Getting this error after setup as new project 

### ISSUE THREAD

**Issue by AamilSilawat26** [flutter-clutter/flutter-simple-edge-detection#20]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':simple_edge_detection:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Admin\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\Aamil'sWorkSpace\simple_edge_detection\android\.cxx\cmake\debug\armeabi-v7a --target native_edge_detection}
  [1/4] Building CXX object CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/edge_detector.cpp.o
  [2/4] Building CXX object CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/native_edge_detection.cpp.o
  [3/4] Building CXX object CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/image_processor.cpp.o
  FAILED: C:\Users\Admin\AppData\Local\Android\Sdk\ndk\22.0.7026061-2\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi16 --gcc-toolchain=C:/Users/Admin/AppData/Local/Android/Sdk/ndk/22.0.7026061-2/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Admin/AppData/Local/Android/Sdk/ndk/22.0.7026061-2/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dnative_edge_detection_EXPORTS -I../../../../../include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -frtti -fexceptions -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/native_edge_detection.cpp.o -MF CMakeFiles\native_edge_detection.dir\F_\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\native_edge_detection.cpp.o.d -o CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/native_edge_detection.cpp.o -c "F:\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\native_edge_detection.cpp"
  depfile has multiple output paths
  FAILED: C:\Users\Admin\AppData\Local\Android\Sdk\ndk\22.0.7026061-2\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi16 --gcc-toolchain=C:/Users/Admin/AppData/Local/Android/Sdk/ndk/22.0.7026061-2/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Admin/AppData/Local/Android/Sdk/ndk/22.0.7026061-2/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dnative_edge_detection_EXPORTS -I../../../../../include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -frtti -fexceptions -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/image_processor.cpp.o -MF CMakeFiles\native_edge_detection.dir\F_\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\image_processor.cpp.o.d -o CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/image_processor.cpp.o -c "F:\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\image_processor.cpp"
  depfile has multiple output paths
  FAILED: C:\Users\Admin\AppData\Local\Android\Sdk\ndk\22.0.7026061-2\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi16 --gcc-toolchain=C:/Users/Admin/AppData/Local/Android/Sdk/ndk/22.0.7026061-2/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Admin/AppData/Local/Android/Sdk/ndk/22.0.7026061-2/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dnative_edge_detection_EXPORTS -I../../../../../include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -frtti -fexceptions -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/edge_detector.cpp.o -MF CMakeFiles\native_edge_detection.dir\F_\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\edge_detector.cpp.o.d -o CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/edge_detector.cpp.o -c "F:\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\edge_detector.cpp"
  depfile has multiple output paths
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by flutter-clutter** [comment]
Okay well, I must say I am really not an expert in the outside UNIX world so I can not give good support for Windows specific issues. I definitely recommend using a UNIX system for development.

But that wont' help you right now, so I have a wild guess: the folder contains a single quote (`Aamil'sWorkSpace`) would you mind putting it anywhere else? Could be that it's not being interpreted literally.

What I also find interesting is these lines:

`CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/edge_detector.cpp.o -MF CMakeFiles\native_edge_detection.dir\F_\Aamil'sWorkSpace\simple_edge_detection\ios\Classes\edge_detector.cpp.o.d -o CMakeFiles/native_edge_detection.dir/F_/Aamil'sWorkSpace/simple_edge_detection/ios/Classes/edge_detector.cpp.o -c`

The first and last line use `/` as a directory separator, the second line uses `\` which is the Windows directory separator.

**Comment by AamilSilawat26** [comment]
Okay, Thank you so much. Error is solved
