### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by abhishekove** [flutter-clutter/flutter-simple-edge-detection#8]
I tried building the project but got this error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':simple_edge_detection:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/abhishek/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/abhishek/Desktop/flutter-simple-edge-detection/android/.cxx/cmake/debug/armeabi-v7a --target native_edge_detection}

  ninja: error: '../../../../src/main/jniLibs/armeabi-v7a/libopencv_java4.so', needed by '/home/abhishek/Desktop/flutter-simple-edge-detection/example/build/simple_edge_detection/intermediates/cmake/debug/obj/armeabi-v7a/libnative_edge_detection.so', missing and no known rule to make it

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by flutter-clutter** [comment]
Hey @abhishekove!
Thank you for your contribution.

It seems to me that you haven't included the OpenCV release into the project. Have you followed the steps documented here: https://github.com/flutter-clutter/flutter-simple-edge-detection#try-out?

**Comment by abhishekove** [comment]
Thanks that worked out for me.
